---
# tasks file for common
- name: Install vim
  ansible.builtin.package:
    name: vim
    state: present

- name: Install which
  ansible.builtin.package:
    name: which
    state: present

- name: configure user
  ansible.builtin.user:
    name: "{{ username }}"
    comment: main user
    groups: users