---
# tasks file for common

# Update pacman db
- name: Update pacman database
  become: yes
  shell:
    cmd: pacman -Syy


- name: Install Common Packages
  become: yes
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ packages }}"

- name: Install Common PIP Pacckages
  pip:
    name: "{{ item }}"
  with_items:
    - "{{ pip_packages }}"


- name: configure user
  ansible.builtin.user:
    name: "{{ username }}"
    comment: main user
    groups: users