---
# tasks file for lxde

- name: Install DE
  ansible.builtin.package:
    name: lxde
    state: present

- name: Configure xinitrc
  copy:
    src: "{{ role_path }}/files/xinitrc"
    dest: /home/{{ username }}/.xinitrc
    mode: 0755
        